[DEFAULT]
Font = LibreBaskerville-Regular.ttf
Size = 25
Colour = (255, 255, 255)
Horizontal offset = 0
Vertical offset = 0

[word]
Font = LibreBaskerville-Regular.ttf
Size = 300

[definition]
Font = LibreBaskerville-Regular.ttf
Size = 45

[pronunciation]
Font = LibreBaskerville-Regular.ttf
Size = 0

[category]
Font = LibreBaskerville-Regular.ttf
Size = 0

[explanation]
Font = LibreBaskerville-Regular.ttf
Size = 0

[example]
Font = LibreBaskerville-Regular.ttf
Size = 0
